"""Add token to user

Revision ID: 11345813ae87
Revises: bffc9808dde5
Create Date: 2022-08-04 20:09:09.086382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11345813ae87'
down_revision = 'bffc9808dde5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
