"""Add name to users table

Revision ID: bffc9808dde5
Revises: a223ac7b107e
Create Date: 2022-07-28 20:31:03.080664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bffc9808dde5"
down_revision = "a223ac7b107e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
