version: '3.9'

networks:
  mysamplenetwork:
    driver: bridge

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mysamplenetwork

  api:
    build: ./api
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mysamplenetwork

  frontend:
    build: ./frontend
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - mysamplenetwork
